### ISSUE TITLE
doesnt flip when there is a dot in style value

### ISSUE THREAD

**Issue by lewie6** [oyvindeh/flipcss#11]
amazing stuff by the way

just thought id highlight a bug...

this _"padding: 0 2em 0 3em"_ will flip to this _"padding: 0 3em 0 2em"_ perfectly fine.

However...
this _"padding: 0 2.5em 0 3.5em"_ will not flip

seems that adding a "." to the padding value stops it from working

**Comment by oyvindeh** [comment]
Thanks! Will try to look into this next week.

**Comment by oyvindeh** [comment]
It seems to work for me, if I add a semicolon after the rule. Without the semicolon it fails. Can you please check if this is the problem?

**Comment by oyvindeh** [comment]
I added a comment about the need for semicolons in the README: https://github.com/operasoftware/flipcss/blob/master/README.md#tips-tricks-and-limitations

**Comment by lewie6** [comment]
doesn't work for me..

```
body {
  padding: 0 2.5em 0 3.5em;
}
```

compiles to 

```
body {
  padding: 0 2.5em 0 3.5em;
}
```

this is my grunt task:

```

    flipcss: {
      app: {
        options: {
          warnings: true,
          flipPseudo: false,
          flipUrls: false,
          flipSelectors: false
        },
        files: {
          '/styles/default-rtl.css': '/styles/default-ltr.css'
        }
      }
    }
```

**Comment by lewie6** [comment]
did some digging...

looks like this...
npm install grunt-flipcss --save-dev

installs version 0.1.2

if i manually add the 0.3.0 files, it all works

guess there is something wrong with versioning. 

if i run _npm view grunt-flipcss versions_ i get.. 

```
[
  0.1.0, 
  0.1.1,  
  0.1.2
]
```
